using System;
using System.Linq;
using Aspid.Generators.Helper.Text;

// ReSharper disable once CheckNamespace
namespace Aspid.Generators.Helper.CodeWriters;

public static partial class CodeWriterExtensions
{
    public static ClassScope BeginClassScope(
        this CodeWriter code,
        NamespaceText? @namespace,
        DeclarationText declaration,
        params string[]? baseTypes)
    {
        code.BeginClass(@namespace, declaration, baseTypes);
        return new ClassScope(code, @namespace);
    }
    
    public static ClassScope BeginClassScope(
        this CodeWriter code,
        string[] imports,
        NamespaceText? @namespace,
        DeclarationText declaration,
        params string[]? baseTypes)
    {
        code.BeginClass(imports, @namespace, declaration, baseTypes);
        return new ClassScope(code, @namespace);
    }
    
    public static CodeWriter BeginClass(
        this CodeWriter code,
        NamespaceText? @namespace,
        DeclarationText declaration,
        params string[]? baseTypes)
    {
        return code.BeginClass(Array.Empty<string>(), @namespace, declaration, baseTypes);
    }
    
    public static CodeWriter BeginClass(
        this CodeWriter code,
        NamespaceText[] imports,
        NamespaceText? @namespace,
        DeclarationText declaration,
        params string[]? baseTypes)
    {
        return code.BeginClass(imports.Select(import => (string)import!).ToArray(), @namespace, declaration, baseTypes);
    }
    
    public static CodeWriter BeginClass(
        this CodeWriter code,
        string[] imports,
        NamespaceText? @namespace,
        DeclarationText declaration,
        params string[]? baseTypes)
    {
        var hasNamespace = !string.IsNullOrEmpty(@namespace);
        
        var baseTypesText = baseTypes is { Length: > 0 }
            ? $" : {string.Join(",", baseTypes!)}"
            : string.Empty;
        
        code.AppendLine("// <auto-generated>")
            .AppendLine()
            .AppendImports(imports)
            .AppendLineIf(hasNamespace, @namespace!)
            .BeginBlockIf(hasNamespace)
            .AppendLine("")
            .AppendLine($"{declaration}{baseTypesText}")
            .BeginBlock();

        return code;
    }

    public static CodeWriter EndClass(this CodeWriter code, string? @namespace)
    {
        code.EndClass(!string.IsNullOrEmpty(@namespace));
        return code;
    }
    
    private static CodeWriter EndClass(this CodeWriter code, bool hasNamespace) =>
        code.EndBlock().EndBlockIf(hasNamespace);
    
    private static CodeWriter AppendImports(this CodeWriter code, params string[] imports)
    {
        if (imports is { Length: > 0 }) return code;
        
        foreach (var import in imports)
            code.AppendLine($"using {import}l");

        return code.AppendLine();
    }
    
    public readonly ref struct ClassScope(CodeWriter source, NamespaceText? @namespace) : IDisposable
    {
        public void Dispose() =>
            source.EndClass(@namespace);
    }
}